add mypy for check types; add config checker; refactors
AITUSAIT/pocket-moodle pull request #52
Opened 2024-02-13 21:35 UTC by DAKExDUCK

2024-02-29 16:01 UTC, DAKExDUCK commented
@Palad1nchik @amdRyzen5600X aksed for review

2024-02-29 16:53 UTC, amdRyzen5600X requested changes

2024-02-29 16:53 UTC, amdRyzen5600X commented on modules/bot/keyboards/moodle.py
в тайп хинтах ты указываешь модуль, а не класс + нужно добавить union с None на kb

2024-02-29 16:53 UTC, amdRyzen5600X commented on modules/bot/handlers/moodle.py
>          message: types.Message = query
присваиваешь переменной типа types.Message экземпляр CallbackQuery

2024-02-29 16:53 UTC, amdRyzen5600X commented on config.py
>  TOKEN_NOTIFY = os.getenv("TOKEN_notify")
на токены тоже нужно добавить дефолт значение и в global_vars.py добавить проверку на дефолтное значение

2024-02-29 16:53 UTC, amdRyzen5600X commented on modules/bot/handlers/default.py
>      if not user:
вторая проверка на not user которая никогда не сработает из-за предудущей проверки

2024-02-29 16:53 UTC, amdRyzen5600X commented on modules/bot/handlers/default.py
>      if not user:
вторая проверка на not user которая никогда не сработает из-за предудущей проверки

2024-03-01 05:47 UTC, amdRyzen5600X requested changes

2024-03-01 05:47 UTC, amdRyzen5600X commented on modules/bot/handlers/default.py
>      kb = None
добавить None | InlineKeyboardMarkup на kb

2024-03-01 06:17 UTC, amdRyzen5600X requested changes

2024-03-01 06:17 UTC, amdRyzen5600X commented on modules/utils/config_utils.py
> +def get_from_env(field: str, default: Any | None = None, value_type: type[str | int | Any] = str):
лучше через generics сделать type hints чтобы можно было указать return type

2024-03-01 06:19 UTC, DAKExDUCK commented on modules/utils/config_utils.py
> +def get_from_env(field: str, default: Any | None = None, value_type: type[str | int | Any] = str):
typing.Generic?

2024-03-09 14:16 UTC, amdRyzen5600X approved these changes

2024-03-09 14:32 UTC, merged