fix /check_finals
AITUSAIT/pocket-moodle pull request #81
Opened 2024-03-30 17:07 UTC by amdRyzen5600X

2024-03-31 07:08 UTC, DAKExDUCK requested changes

2024-03-31 07:08 UTC, DAKExDUCK commented on .dockerignore
> -**/.env
а зачем? чтобы в image попал .env а потом слили токены, креды в бд и тд?

2024-03-31 10:23 UTC, amdRyzen5600X commented on .dockerignore
> -**/.env
а как тогда в проде он получает креды + в пм апдейтс нет .енв в докеригноре

2024-04-01 02:12 UTC, DAKExDUCK commented on .dockerignore
> -**/.env
через env параметры при запуске контейнера или compose файл

кстати тогда на апдейтс надо бы добавить

2024-04-02 08:10 UTC, DAKExDUCK approved these changes

2024-04-02 08:21 UTC, merged