upgrade python version
AITUSAIT/pocket-moodle pull request #84
Opened 2024-04-18 17:02 UTC by DAKExDUCK

2024-04-22 10:02 UTC, amdRyzen5600X commented on modules/bot/throttling.py
> +            elif isinstance(event, CallbackQuery):
оно должно дважды проверять event на один и тот же класс?

2024-04-24 10:22 UTC, DAKExDUCK commented on modules/bot/throttling.py
> +            elif isinstance(event, CallbackQuery):
а ой, там должно быть Message в одном из них

2024-05-27 10:34 UTC, amdRyzen5600X requested changes

2024-05-27 10:34 UTC, amdRyzen5600X commented on modules/bot/handlers/secondary.py
>          lambda c: c.data == "convert",
оберни все лябда функции в реистрах хендлеров в aiogram.F.func()

2024-05-27 10:34 UTC, amdRyzen5600X commented on main.py
>      setup(app, EncryptedCookieStorage(str.encode(os.getenv("COOKIE_KEY", "COOKIE"))))
добавь старт пулинга и бот таску в глобал варс

2024-05-27 10:35 UTC, DAKExDUCK commented on main.py
>      setup(app, EncryptedCookieStorage(str.encode(os.getenv("COOKIE_KEY", "COOKIE"))))
а нам один хуй не нужна глобал таска, наверное

2024-05-27 10:36 UTC, DAKExDUCK commented on modules/bot/handlers/secondary.py
>          lambda c: c.data == "convert",
бля пизда долбаебы придумали нахуй

2024-06-04 11:06 UTC, amdRyzen5600X commented on modules/bot/handlers/secondary.py
>      await CONVERT.wait_files.set()
разве чтобы поставить стейт нужно не так сделать
```python
await state.set_state(CONVERT.wait_files)
```

2024-06-04 11:07 UTC, amdRyzen5600X commented on modules/bot/handlers/secondary.py
>      async with state.proxy() as data:
data на state же через state.set_data() делается + у меня lsp показывает ошибку что у state нет proxy

2024-06-04 11:21 UTC, DAKExDUCK commented on modules/bot/handlers/secondary.py
>      async with state.proxy() as data:
Это понятно, у меня линтеры тоже показывают. Руки до этого не дошли

2024-06-04 11:22 UTC, DAKExDUCK commented on modules/bot/handlers/secondary.py
>      await CONVERT.wait_files.set()
Не смотрел

2024-06-17 13:53 UTC, merged